### PR TITLE
JOSS editorial tweaks

### PR DESCRIPTION
**Pull request by warrickball**
Some finishing touches ahead of publication in JOSS following a [successful review](https://github.com/openjournals/joss-reviews/issues/7273). These are mostly to choose one form of "raytracing", and specifically that form for consistency with the title.

Note I haven't suggested a correction to this sentence, which needs fixing (emphasis mine):
> This feature could potentially be seen in the near future **with a recent as a space extension** to the EHT aimed of detection and measurement (Lupsasca et al., 2024).

It isn't unambiguous to me what the intended meaning is so I'll leave it to you to fix.

### CODE REVIEW

**Comment by dominic-chang** [comment]
Are you able to change the branch of the pull request to [joss-paper](https://github.com/dominic-chang/Krang.jl/tree/joss-paper) instead of main? I seem to be unable to on my end for some reason

**Comment by dominic-chang** [comment]
Thanks I fixed the sentence and have changed all instances of "raytracing" to "ray tracing" except in the tag and title where it has been changed to "ray-tracing". Hopefully that is ok

**Comment by warrickball** [comment]
Sorry, I forgot the PR didn't automatically target the branch I switched from. It looks like you still need to merge `joss-editorial-tweaks` into `joss-paper` for the JOSS pipeline to pick up the changes.

I also noticed a CI failure crept in but this seems unrelated to any changes here.

Finally, regarding raytracing/ray tracing, I think we need consistency everywhere, which is why I went with "raytracing" for consistency in the title. I don't mind "ray tracing", which might be more common, but then the title (of the paper and the Zenodo archive) needs to change to "ray tracer", and any adjective "ray tracing" should be "ray-tracing" (as in a "ray-tracing techniques", though that particular instance can probably just be "ray tracing" without changing the meaning).

**Comment by dominic-chang** [comment]
> I also noticed a CI failure crept in but this seems unrelated to any changes here.

Yeah, the CI failure is due to a broken Enzyme rule in one of the dependencies I manage. I'm trying to get that fixed. 

> I think we need consistency everywhere, which is why I went with "raytracing" for consistency in the title.

Ah, ok. I think I'll change everything back to "raytracing" then. Unfortunate that past me made a decision without checking on how things were spelled.

**Comment by dominic-chang** [comment]
Ok, I think the paper should be all good now. I also fixed the bug that stopped the docs from building on CI

https://github.com/dominic-chang/Krang.jl/tree/joss-paper

**Pull request merged**
